global:

  # prefix to storage files - not so important
  cluster_id: "balmas1"
  
  # private repository where all vod images stored
  private_registry: "artifactory.rnd-hub.com:5000/dd_vod/"
  
  image_pull_secret:
    
    # true - for signing in with credentials (secret), false if image_pull_secret is not needed.
    enabled: true

    # true - for using pre made secret, false for creating secret with user&pass
    use_existing: true
    name: artifactory-dd-vod
    username: ""
    password: ""
  
  # 
  storage:
    # empty for default storage class, fill for non-default storage class, "-" for not using pre made storage class
      storage_class: "nfs-client"

    pvc:
      # if storage_class: "-", fill this nfs keys
      nfs_host: ""
      nfs_root: ""
      
      
  
  # ignore (label for deployment)
  group: "rms"


  base_url_host: "10.40.134.6"
  
  # 443 for https
  base_url_port: "80"
  base_url_path: "/rms"

  # true for https
  base_url_secured: "false"

  redis_ha: false

  # true to enable recording
  recording:
    enabled: false
  
  # size of resources used by the vod 
  sizing_mode: small


# images pointers on private repository

rms_ui:
  image:
    repository: vod/rms-ui
    tag: v4.0.9

rms_control:
  image:
    repository: vod/rms-control
    tag: v4.0.6

auth:
  image:
    repository: vod/auth
    tag: v4.0.11

catalog:
  image:
    repository: vod/catalog
    tag: v4.0.6

kurento_cluster:
  image:
    repository: vod/kurento-cluster
    tag: v4.0.6
  
  # ignore
  replicas: 1

kurento:
  image:
    repository: vod/kurento
    tag: v4.0.6
  
  # ignore
  heapster_dns_service_name: heapster.kube-system
  
  # number of kurento pods
  replicas: 1

# webrtc proxy
coturn:
  enable: true
  image:
    repository: instrumentisto/coturn
    tag: 4.5.2
  
  # specify cluster nodes that you want viewers to use coturn that runs on them, specific syntax 
  #  turn - webrtc proxy
  #  stun - service that provides external ip to chrome
  stun: 
    - urls: 
      - turn:10.40.134.7:3478
      - stun:10.40.134.7:3478

      # ignore
      username: rms

      # ignore
      credential: rms
  
  # choose port range webrtc traffic from cluster to viewers
  ports:
    min: 12000
    max: 12200

online_sensors_detection:
  enabled: false
  image:
    repository: vod/online-sensors-detection
    tag: v4.0.7

sds:
  image:
    repository: vod/sds
    tag: v4.0.6

supervisor:
  image:
    repository: vod/supervisor
    tag: v4.0.9

# signalling responsible for establish connection between webrtc two servers
signalling:
  image:
    repository: vod/signalling
    tag: v4.0.9
  
  # video quality
  webrtc_bitrate_kbps: 1500

simulator:
  image:
    repository: vod/simulator
    tag: v4.0.10

vaas:
  image:
    repository: vod/vaas
    tag: v4.0.6

  # number of vass pods - backend for streaming
  replicas: 1

vod_service:
  image:
    repository: vod/vod-service
    tag: v4.0.6

# if recording:true - responsible for proccesing and saving the input video
worker_recording:
  image:
    repository: vod/recording-worker
    tag: v4.0.9

  # number or recording-worker pods, need to match the number of video streams (channels) that need to be recorded
  replicas: 1

# responsible for streaming video to viewrs
streaming_worker:
  image:
    repository: vod/streaming-worker
    tag: v4.0.13
  
  # need to match the number of video streams (channels)
  replicas: 1

  # for du - document later
  per_host_restriction: "false"

# if recording:true, responsible for deleteing old recordings
recording_curator:
  image:
    repository: vod/recording-curator
    tag: v4.0.7
  enable: true
  # how many hours video history to keep
  recording_retention_hours: 360

# version of recording curator
systemversion: 4.0.20
fullSystemVersion: 4.0.20-1638696285452